const SB='https://wsuwnmrbdcorercrtcgy.supabase.co';
const KEY='sb_publishable_4uTDBH31bP62rvnB59ee1A_iQvnqLEC';
const H={apikey:KEY,Authorization:'Bearer '+KEY};
const $=id=>document.getElementById(id);
const q=async p=>{const r=await fetch(SB+'/rest/v1/'+p,{headers:H});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-GB');
const money=n=>n==null?'—':'£'+Number(n).toFixed(2);
const safe=u=>/^https:\/\//i.test(String(u||''))?String(u):'';
const when=s=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
let latest=null,prev=null,products=[],prevMap=new Map(),structures=[],history=[];
function productCell(x){const link=safe(x.source_url)||`https://www.amazon.co.uk/dp/${encodeURIComponent(x.asin)}`;const img=safe(x.image_url);return `<div class="product">${img?`<img class="thumb" loading="lazy" src="${esc(img)}" alt="">`:'<div class="ph">暂无<br>主图</div>'}<div><div class="ptitle"><a href="${esc(link)}" target="_blank" rel="noopener">${esc(x.title||'未获取标题')}</a></div><div class="asin">${esc(x.asin)}${x.brand?' · '+esc(x.brand):''}</div></div></div>`}
function diff(x){const p=prevMap.get(x.asin);const old=p?.category_rank??x.previous_rank??null;return {old,delta:old==null?null:old-x.category_rank,prev:p}}
function moveCell(d){if(d.delta==null)return '<span class="flat">—</span>';if(d.delta>0)return `<span class="up">↑ ${fmt(d.delta)}</span>`;if(d.delta<0)return `<span class="down">↓ ${fmt(Math.abs(d.delta))}</span>`;return '<span class="flat">0</span>'}
function tags(x){return [x.product_type,x.colour_style].filter(Boolean).flatMap(v=>String(v).split('/')).slice(0,3).map(v=>`<span class="tag">${esc(v)}</span>`).join('')||'—'}
function signalFor(x){const d=diff(x),arr=[];if(x.category_rank<=100&&(d.old==null||d.old>100))arr.push('<span class="badge info">新进≤100</span>');if((d.delta||0)>=50)arr.push('<span class="badge good">快速前移</span>');else if((d.delta||0)>=20)arr.push('<span class="badge good">明显上涨</span>');if((d.delta||0)<=-20)arr.push('<span class="badge bad">明显下滑</span>');if(d.prev&&x.price_gbp!=d.prev.price_gbp)arr.push('<span class="badge warn">价格变化</span>');if(d.prev&&x.review_count!=d.prev.review_count)arr.push('<span class="badge info">评论变化</span>');return arr.join(' ')||'<span class="badge warn">观察</span>'}
function typeOptions(){const types=[...new Set(products.map(x=>x.product_type).filter(Boolean))].sort();['changeType','midType'].forEach(id=>{const s=$(id),v=s.value;s.innerHTML='<option value="">全部产品类型</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('');s.value=v})}
function renderChanges(){const term=$('changeSearch').value.trim().toLowerCase(),typ=$('changeType').value,rule=$('changeRule').value;let rows=products.filter(x=>{const d=diff(x);const big=Math.abs(d.delta||0)>=20,newTop=x.category_rank<=100&&(d.old==null||d.old>100),changed=d.prev&&(x.price_gbp!=d.prev.price_gbp||x.review_count!=d.prev.review_count||x.sales_estimate!=d.prev.sales_estimate);if(!(big||newTop||changed))return false;if(typ&&x.product_type!==typ)return false;if(term&&!`${x.asin} ${x.title||''} ${x.brand||''}`.toLowerCase().includes(term))return false;if(rule==='big'&&!big)return false;if(rule==='up'&&!((d.delta||0)>=20))return false;if(rule==='new'&&!newTop)return false;return true}).sort((a,b)=>{const da=diff(a),db=diff(b);return Math.abs(db.delta||0)-Math.abs(da.delta||0)});$('changeCount').textContent=`${rows.length} 个符合条件的 ASIN`;$('changeRows').innerHTML=rows.length?rows.map(x=>{const d=diff(x);return `<tr><td>${productCell(x)}</td><td class="rank">#${fmt(x.category_rank)}</td><td>${d.old==null?'—':'#'+fmt(d.old)}</td><td>${moveCell(d)}</td><td>${money(x.price_gbp)}</td><td>${fmt(x.sales_estimate)}</td><td>${x.rating??'—'} / ${fmt(x.review_count)}</td><td>${fmt(x.days_since_launch)}</td><td>${signalFor(x)}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">当前筛选条件下暂无异动商品。</td></tr>';bindImgs()}
function midJudge(x){const d=diff(x);if((d.delta||0)>=50&&x.sales_estimate!=null)return '<span class="badge good">重点跟进</span>';if((d.delta||0)>=20)return '<span class="badge info">前移观察</span>';if(x.days_since_launch!=null&&x.days_since_launch<=180)return '<span class="badge warn">新品观察</span>';return '<span class="badge warn">持续观察</span>'}
function renderMid(){const term=$('midSearch').value.trim().toLowerCase(),typ=$('midType').value,sort=$('midSort').value;let rows=products.filter(x=>x.category_rank>=200&&x.category_rank<=400).filter(x=>(!typ||x.product_type===typ)&&(!term||`${x.asin} ${x.title||''} ${x.brand||''}`.toLowerCase().includes(term)));rows.sort((a,b)=>{const da=diff(a),db=diff(b);if(sort==='rank')return a.category_rank-b.category_rank;if(sort==='sales')return (b.sales_estimate??-1)-(a.sales_estimate??-1);if(sort==='newest')return (a.days_since_launch??99999)-(b.days_since_launch??99999);return (db.delta??-99999)-(da.delta??-99999)});$('midCount').textContent=`${rows.length} 个 ASIN`;$('midRows').innerHTML=rows.length?rows.map(x=>{const d=diff(x);return `<tr><td>${productCell(x)}</td><td class="rank">#${fmt(x.category_rank)}</td><td>${d.old==null?'—':'#'+fmt(d.old)}</td><td>${moveCell(d)}</td><td>${money(x.price_gbp)}</td><td>${fmt(x.sales_estimate)}</td><td>${x.rating??'—'} / ${fmt(x.review_count)}</td><td>${fmt(x.days_since_launch)}</td><td>${midJudge(x)}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">当前没有 #200–400 数据。</td></tr>';bindImgs()}
function bars(id,dim){const rows=structures.filter(x=>x.dimension===dim).slice(0,12),max=Math.max(1,...rows.map(x=>Number(x.item_count)||0));$(id).innerHTML=rows.length?rows.map(x=>`<div class="barrow"><div title="${esc(x.label)}">${esc(x.label)}</div><div class="bar"><span style="width:${Math.max(3,(Number(x.item_count)||0)/max*100)}%"></span></div><div>${fmt(x.item_count)}</div></div>`).join(''):'<div class="empty">暂无结构数据。</div>'}
function renderStructure(){bars('typeBars','product_type');bars('colourBars','colour_style');$('structureRows').innerHTML=structures.length?structures.map(x=>`<tr><td>${x.dimension==='product_type'?'产品类型':x.dimension==='colour_style'?'颜色/风格':esc(x.dimension)}</td><td>${esc(x.label)}</td><td>${fmt(x.item_count)}</td><td>${x.share_pct==null?'—':Number(x.share_pct).toFixed(1)+'%'}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">暂无结构数据。</td></tr>';$('structureNote').textContent=`共 ${structures.length} 个结构标签`}
function renderHistory(){const live=history.filter(r=>r.source==='local_chrome_sellersprite').slice(0,8),max=Math.max(1,...live.map(r=>Number(r.top100_count)||0));$('historyList').innerHTML=live.length?live.map(r=>`<div class="hrow"><div>${when(r.collected_at)}</div><div class="mini"><span style="width:${Math.max(3,(Number(r.top100_count)||0)/max*100)}%"></span></div><div>≤100 ${fmt(r.top100_count)}</div><div>#200–400 ${fmt(r.midband_count)}</div><div>${money(r.median_price_gbp)}</div></div>`).join(''):'<div class="empty">暂无实时采集批次。</div>'}
function renderOverview(){const top=products.filter(x=>x.category_rank<=100);$('kTotal').textContent=fmt(products.length);$('kTop').textContent=fmt(top.length);$('kDistinct').textContent=fmt(new Set(top.map(x=>x.category_rank)).size);$('kMid').textContent=fmt(products.filter(x=>x.category_rank>=200&&x.category_rank<=400).length);$('kNew').textContent=fmt(latest.new_top100_count);$('kSales').textContent=fmt(products.filter(x=>x.sales_estimate!=null).length);$('kImages').textContent=fmt(products.filter(x=>x.image_url).length);$('kPrice').textContent=money(latest.median_price_gbp);$('kTime').textContent='最近采集：'+when(latest.collected_at);$('compareTime').textContent=`上一批次：${when(prev?.collected_at)}`;
let overlap=0,changed=0,big=0,pchg=0,rchg=0,schg=0;for(const x of products){const d=diff(x);if(!d.prev)continue;overlap++;if(x.category_rank!==d.prev.category_rank)changed++;if(Math.abs((d.prev.category_rank??x.category_rank)-x.category_rank)>=20)big++;if(x.price_gbp!=d.prev.price_gbp)pchg++;if(x.review_count!=d.prev.review_count)rchg++;if(x.sales_estimate!=d.prev.sales_estimate)schg++;} $('cOverlap').textContent=fmt(overlap);$('cChanged').textContent=fmt(changed);$('cBig').textContent=fmt(big);$('cPrice').textContent=fmt(pchg);$('cReview').textContent=fmt(rchg);$('cSales').textContent=fmt(schg);
const mids=products.filter(x=>x.category_rank>=200&&x.category_rank<=400).map(x=>({x,d:diff(x)})).sort((a,b)=>(b.d.delta??-9999)-(a.d.delta??-9999));const newT=products.filter(x=>x.category_rank<=100&&(diff(x).old==null||diff(x).old>100));const lines=[];if(newT.length)lines.push(`<div class="source"><b>新进≤100：</b>${newT.slice(0,5).map(o=>esc(o.asin)+' #'+o.category_rank).join(' · ')}${newT.length>5?' 等':''}</div>`);const fast=mids.filter(o=>(o.d.delta||0)>=20);if(fast.length)lines.push(`<div class="source"><b>#200–400 向前突破：</b>${fast.slice(0,5).map(o=>esc(o.x.asin)+' #'+o.x.category_rank+' ↑'+o.d.delta).join(' · ')}</div>`);const young=mids.filter(o=>o.x.days_since_launch!=null&&o.x.days_since_launch<=180&&o.x.sales_estimate!=null);if(young.length)lines.push(`<div class="source"><b>中段新品：</b>${young.slice(0,5).map(o=>esc(o.x.asin)+' '+o.x.days_since_launch+'天').join(' · ')}</div>`);$('signals').innerHTML=lines.join('')||'<div class="empty">本轮暂未发现达到重点阈值的信号。</div>';$('sourceStatus').innerHTML=`<b>状态：</b>${esc(latest.source_status||'unknown')}<br><b>来源：</b>${esc(latest.source||'—')}<br><b>说明：</b>${esc(latest.source_note||'—')}`}
function bindImgs(){document.querySelectorAll('img.thumb:not([data-b])').forEach(img=>{img.dataset.b='1';img.onerror=()=>{const d=document.createElement('div');d.className='ph';d.innerHTML='图片<br>加载失败';img.replaceWith(d)}})}
async function load(){try{$('livePill').textContent='正在读取最新批次…';const runs=await q('monitor_runs?select=*&category_key=eq.party_balloons&order=collected_at.desc&limit=12');history=runs;latest=runs[0];prev=runs.find(r=>r.id!==latest.id&&r.source==='local_chrome_sellersprite')||runs[1];if(!latest)throw new Error('暂无采集批次');const [cur,pre,st]=await Promise.all([q(`product_snapshots?select=*&run_id=eq.${latest.id}&order=category_rank.asc.nullslast`),prev?q(`product_snapshots?select=*&run_id=eq.${prev.id}`):Promise.resolve([]),q(`structure_snapshots?select=*&run_id=eq.${latest.id}&order=dimension.asc,item_count.desc`)]);products=cur;prevMap=new Map(pre.map(x=>[x.asin,x]));structures=st;$('livePill').textContent='● 动态后台已连接';$('livePill').className='pill live';renderOverview();typeOptions();renderChanges();renderMid();renderStructure();renderHistory()}catch(e){$('livePill').textContent='后台连接异常';$('livePill').className='pill warn';$('sourceStatus').textContent=e.message;console.error(e)}}
[...document.querySelectorAll('.tabs button')].forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
['changeSearch','changeType','changeRule'].forEach(id=>$(id).addEventListener(id==='changeSearch'?'input':'change',renderChanges));['midSearch','midType','midSort'].forEach(id=>$(id).addEventListener(id==='midSearch'?'input':'change',renderMid));
load();setInterval(load,300000);