const SB='https://wsuwnmrbdcorercrtcgy.supabase.co';
const KEY='sb_publishable_4uTDBH31bP62rvnB59ee1A_iQvnqLEC';
const H={apikey:KEY,Authorization:'Bearer '+KEY};
const $=id=>document.getElementById(id);
const q=async p=>{const r=await fetch(SB+'/rest/v1/'+p,{headers:H});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-GB');
const money=n=>n==null?'—':'£'+Number(n).toFixed(2);
const pct=n=>Number.isFinite(n)?Number(n).toFixed(1)+'%':'—';
const when=s=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
const safe=u=>/^https:\/\//i.test(String(u||''))?String(u):'';
const median=a=>{const v=a.filter(x=>x!=null&&Number.isFinite(Number(x))).map(Number).sort((x,y)=>x-y);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2};
const ratio=(n,d)=>d?100*n/d:0;
let runs=[],latest=null,prev=null,prev2=null,products=[],prevProducts=[],prev2Products=[],prevMap=new Map(),prev2Map=new Map(),selectedDim='product_type';

function productCell(x){const link=safe(x.source_url)||`https://www.amazon.co.uk/dp/${encodeURIComponent(x.asin)}`;const img=safe(x.image_url);return `<div class="product">${img?`<img class="thumb" loading="lazy" src="${esc(img)}" alt="">`:'<div class="ph">暂无<br>主图</div>'}<div><div class="ptitle"><a href="${esc(link)}" target="_blank" rel="noopener">${esc(x.title||'未获取标题')}</a></div><div class="asin">${esc(x.asin)}${x.brand?' · '+esc(x.brand):''}</div></div></div>`}
function rankDiff(x){const p=prevMap.get(x.asin);const old=p?.category_rank??x.previous_rank??null;return {old,delta:old==null?null:Number(old)-Number(x.category_rank),prev:p}}
function trend(x){const a=prev2Map.get(x.asin)?.category_rank??null,b=prevMap.get(x.asin)?.category_rank??null,c=x.category_rank??null;return [a,b,c].map(v=>v==null?'—':'#'+fmt(v)).join(' → ')}
function moveHtml(d){if(d.delta==null)return '—';if(d.delta>0)return `<span class="move-up">↑ ${fmt(d.delta)}</span>`;if(d.delta<0)return `<span class="move-down">↓ ${fmt(Math.abs(d.delta))}</span>`;return '<span>0</span>'}
function productTags(x){return [x.product_type,x.colour_style,x.occasion].filter(Boolean).flatMap(v=>String(v).split('/')).slice(0,4).map(v=>`<span class="tag">${esc(v)}</span>`).join('')||'—'}
function isNewTop(x){const d=rankDiff(x);return x.category_rank<=100&&(d.old==null||d.old>100)}
function broke200(x){const d=rankDiff(x);return x.category_rank<200&&d.old!=null&&d.old>=200}
function priority(x){const d=rankDiff(x),a=Math.abs(d.delta||0);if((d.delta||0)>=50||broke200(x)||isNewTop(x))return 'p0';if(a>=50||(d.delta||0)>=20)return 'p1';if(a>=20||(d.delta||0)>0)return 'p2';return 'p3'}
function priorityLabel(p){return p==='p0'?'P0 极速前移':p==='p1'?'P1 强异动':p==='p2'?'P2 明显异动':'P3 一般波动'}
function priceBand(p){if(p==null)return '未知';p=Number(p);if(p<5)return '<£5';if(p<7)return '£5–6.99';if(p<10)return '£7–9.99';if(p<15)return '£10–14.99';return '≥£15'}
function splitVal(dim,v){if(v==null||v==='')return [];const s=String(v).trim();if(!s)return[];if(['product_type','colour_style','occasion','material'].includes(dim))return s.split(/\s*[/|,]\s*/).map(x=>x.trim()).filter(Boolean);return [s]}
function structureFor(list,dim){const c=new Map();list.forEach(x=>splitVal(dim,x[dim]).forEach(v=>c.set(v,(c.get(v)||0)+1)));return new Map([...c].map(([k,n])=>[k,{count:n,share:ratio(n,list.length)}]))}
function structureRows(dim){const c=structureFor(products,dim),p=structureFor(prevProducts,dim),p2=structureFor(prev2Products,dim);const labels=[...new Set([...c.keys(),...p.keys(),...p2.keys()])];return labels.map(label=>{const cv=c.get(label)||{count:0,share:0},p1=p.get(label)||{count:0,share:0},p0=p2.get(label)||{count:0,share:0},base=(p1.share+p0.share)/2;return {label,count:cv.count,share:cv.share,base,growth:cv.share-base,trend:[p0.share,p1.share,cv.share]}}).filter(x=>x.count>0).sort((a,b)=>b.share-a.share)}
function structureGrowthMap(){const rows=[...structureRows('product_type'),...structureRows('occasion')];return new Map(rows.map(x=>[x.label,x.growth]))}
function opportunityScore(x){const d=rankDiff(x);let s=8;const delta=d.delta||0;if(delta>0)s+=Math.min(34,Math.round(delta/8));if(x.category_rank<=100)s+=20;else if(x.category_rank<200)s+=14;else if(x.category_rank<=400)s+=9;if(x.days_since_launch!=null){if(x.days_since_launch<=90)s+=18;else if(x.days_since_launch<=180)s+=13;else if(x.days_since_launch<=365)s+=6}if(x.sales_estimate!=null){if(x.sales_estimate>=100)s+=12;else if(x.sales_estimate>=50)s+=8;else if(x.sales_estimate>=20)s+=4}if(x.review_count!=null){if(x.review_count<=20)s+=8;else if(x.review_count<=100)s+=5}if(isNewTop(x))s+=8;if(broke200(x))s+=8;const gm=structureGrowthMap();const gs=splitVal('product_type',x.product_type).concat(splitVal('occasion',x.occasion)).reduce((m,k)=>Math.max(m,gm.get(k)||0),0);if(gs>1)s+=6;else if(gs>0.3)s+=3;return Math.min(99,Math.round(s))}
function opportunityType(x){const d=rankDiff(x),gm=structureGrowthMap();const gs=splitVal('product_type',x.product_type).concat(splitVal('occasion',x.occasion)).reduce((m,k)=>Math.max(m,gm.get(k)||0),0);if((x.days_since_launch??9999)<=180&&(d.delta||0)>0)return '🌱 新品型';if((d.delta||0)>=50)return '🔥 爆发型';if(gs>1)return '🧩 结构增长型';if(x.price_gbp!=null&&['£7–9.99','£10–14.99'].includes(priceBand(x.price_gbp)))return '💰 价格机会型';return '👀 持续观察型'}
function reasons(x){const d=rankDiff(x),r=[];if((d.delta||0)>=50)r.push(['快速前移','good']);else if((d.delta||0)>=20)r.push(['排名上升','good']);if((x.days_since_launch??9999)<=90)r.push(['≤90天新品','info']);else if((x.days_since_launch??9999)<=180)r.push(['≤180天新品','info']);if((x.review_count??9999)<=20)r.push(['低评论门槛','warn']);if((x.sales_estimate??0)>=100)r.push(['销量≥100','good']);if(isNewTop(x))r.push(['新进≤100','info']);if(broke200(x))r.push(['突破#200','good']);return (r.length?r:[['值得持续观察','']]).map(([t,c])=>`<span class="reason ${c}">${t}</span>`).join('')}
function breakthroughScore(x){const d=rankDiff(x);let s=30;if((d.delta||0)>0)s+=Math.min(35,Math.round(d.delta/3));s+=Math.max(0,Math.round((400-x.category_rank)/20));if((x.days_since_launch??9999)<=180)s+=8;if((x.sales_estimate??0)>=50)s+=8;return Math.min(99,s)}

function renderHeader(){const top=products.filter(x=>x.category_rank<=100),prevTop=prevProducts.filter(x=>x.category_rank<=100);const newTop=top.filter(isNewTop).length;const currentMap=new Map(products.map(x=>[x.asin,x]));const exits=prevTop.filter(x=>!currentMap.has(x.asin)||currentMap.get(x.asin).category_rank>100).length;const churn=ratio(newTop+exits,prevTop.length||top.length);const young=top.filter(x=>(x.days_since_launch??9999)<=180).length;const p0=products.filter(x=>priority(x)==='p0').length;const mid=products.filter(x=>x.category_rank>=200&&x.category_rank<=400);const topDelta=top.length-prevTop.length,midDelta=mid.length-prevProducts.filter(x=>x.category_rank>=200&&x.category_rank<=400).length;
$('kTop').textContent=fmt(top.length);$('kTopDelta').innerHTML=`<span class="${topDelta>=0?'delta-up':'delta-down'}">${topDelta>=0?'↑':'↓'} ${Math.abs(topDelta)}</span> vs 上轮`;$('kMid').textContent=fmt(mid.length);$('kMidDelta').innerHTML=`<span class="${midDelta>=0?'delta-up':'delta-down'}">${midDelta>=0?'↑':'↓'} ${Math.abs(midDelta)}</span> vs 上轮`;$('kTotal').textContent=fmt(products.length);$('kPrice').textContent=money(latest.median_price_gbp);$('kChurn').textContent=pct(churn);$('kChurnNote').textContent=`新进 ${newTop} · 退出 ${exits}`;$('kP0').textContent=fmt(p0);$('kYoungShare').textContent=pct(ratio(young,top.length));$('kTime').textContent=when(latest.collected_at).replace(/:\d{2}$/,'');$('kPrevTime').textContent='与上轮 '+when(prev?.collected_at).replace(/:\d{2}$/,'')+' 对比';
const bands=priceBandStats(),best=[...bands].filter(x=>x.n>=8).sort((a,b)=>(b.topRate+b.newRate+b.strongRate)-(a.topRate+a.newRate+a.strongRate))[0];const sg=[...structureRows('product_type'),...structureRows('occasion')].filter(x=>x.growth>0).sort((a,b)=>b.growth-a.growth)[0];const summary=[];summary.push(churn>=15?'头部换手明显加快':churn>=8?'头部存在活跃换手':'头部结构相对稳定');if(p0)summary.push(`${p0} 个P0级上升机会`);if(newTop)summary.push(`${newTop} 个样本新进≤100`);if(best)summary.push(`${best.band} 价格带机会评分靠前`);if(sg)summary.push(`${sg.label} 占比提升 ${sg.growth.toFixed(2)}pct`);$('summaryText').textContent=summary.join('；')+'。';$('summaryTime').textContent='数据 '+when(latest.collected_at);
const lights=[['头部换手',churn>=10?'↑':'→',churn>=10?'up':''],['新品活跃',ratio(young,top.length)>=30?'↑':'→',ratio(young,top.length)>=30?'up':''],['价格',priceChangeCount()<=10?'稳定':'波动',priceChangeCount()<=10?'':'down'],['结构变化',sg&&sg.growth>=1?'↑':'→',sg&&sg.growth>=1?'up':'']];$('marketLights').innerHTML=lights.map(([a,b,c])=>`<span class="state-chip ${c}">${a} ${b}</span>`).join('')}
function priceChangeCount(){let n=0;products.forEach(x=>{const p=prevMap.get(x.asin);if(p&&x.price_gbp!=p.price_gbp)n++});return n}
function renderRadar(){const ds=products.map(x=>({x,d:rankDiff(x)}));const ups=ds.filter(o=>(o.d.delta||0)>0),maxUp=ups.sort((a,b)=>(b.d.delta||0)-(a.d.delta||0))[0];const breakout=products.filter(broke200).length;const p0=products.filter(x=>priority(x)==='p0').length;$('radarBreakout').innerHTML=`<div class="radar-line"><b>${p0} 个 P0机会</b><small>极速前移 / 关键突破</small></div><div class="radar-line"><b>${maxUp?`最大前移 +${maxUp.d.delta}`:'暂无强前移'}</b><small>${maxUp?esc(maxUp.x.asin):'等待下一轮'}</small></div><div class="radar-line"><b>${breakout} 个突破 #200</b><small>从中段进入更高排名区</small></div>`;
const young90=products.filter(x=>(x.days_since_launch??9999)<=90).length,young180=products.filter(x=>(x.days_since_launch??9999)<=180).length,youngMove=products.filter(x=>(x.days_since_launch??9999)<=180&&(rankDiff(x).delta||0)>=20).length;$('radarNew').innerHTML=`<div class="radar-line"><b>${young90} 个 ≤90天新品</b><small>${young180} 个 ≤180天新品</small></div><div class="radar-line"><b>${youngMove} 个新品前移≥20</b><small>新品突破效率</small></div><div class="radar-line"><b>${pct(ratio(products.filter(x=>x.category_rank<=100&&(x.days_since_launch??9999)<=180).length,products.filter(x=>x.category_rank<=100).length))}</b><small>Top100新品占比</small></div>`;
const bands=priceBandStats(),best=bands.filter(x=>x.n>=8).sort((a,b)=>(b.topRate+b.newRate+b.strongRate)-(a.topRate+a.newRate+a.strongRate))[0];$('radarPrice').innerHTML=best?`<div class="radar-line"><b>${best.band}</b><small>综合机会最值得观察</small></div><div class="radar-line"><b>${pct(best.topRate)} 进入≤100</b><small>新品率 ${pct(best.newRate)}</small></div><div class="radar-line"><b>${pct(best.strongRate)} 强前移</b><small>排名前移≥20</small></div>`:'<div class="empty">价格数据不足</div>';
const gs=[...structureRows('product_type'),...structureRows('occasion')].filter(x=>x.growth>0).sort((a,b)=>b.growth-a.growth).slice(0,3);$('radarStructure').innerHTML=gs.length?gs.map(x=>`<div class="radar-line"><b>${esc(x.label)} <span class="positive">+${x.growth.toFixed(2)}pct</span></b><small>当前占比 ${x.share.toFixed(1)}%</small></div>`).join(''):'<div class="empty">暂无明显增长结构</div>'}
function renderNewAbility(){const top=products.filter(x=>x.category_rank<=100),mid=products.filter(x=>x.category_rank>=200&&x.category_rank<=400);const vals=[['≤90天新品',products.filter(x=>(x.days_since_launch??9999)<=90).length],['≤180天新品',products.filter(x=>(x.days_since_launch??9999)<=180).length],['Top100 ≤180天',top.filter(x=>(x.days_since_launch??9999)<=180).length],['#200–400 ≤180天',mid.filter(x=>(x.days_since_launch??9999)<=180).length],['新品前移≥20',products.filter(x=>(x.days_since_launch??9999)<=180&&(rankDiff(x).delta||0)>=20).length],['Top100上架中位数',median(top.map(x=>x.days_since_launch))==null?'—':Math.round(median(top.map(x=>x.days_since_launch)))+'天']];$('newMetrics').innerHTML=vals.map(([a,b])=>`<div class="mini-metric"><span>${a}</span><b>${b}</b></div>`).join('');const share=ratio(top.filter(x=>(x.days_since_launch??9999)<=180).length,top.length);$('newBadge').textContent=share>=35?'新品通道活跃':share>=20?'新品通道中等':'新品通道偏弱';$('newInsight').textContent=`Top100中 ${share.toFixed(1)}% 为180天内新品；本轮有 ${products.filter(x=>(x.days_since_launch??9999)<=180&&(rankDiff(x).delta||0)>=20).length} 个新品排名前移≥20。`}
function renderThreshold(){const groups=[products.filter(x=>x.category_rank<=100),products.filter(x=>x.category_rank>=200&&x.category_rank<=400)];const specs=[['评论数中位数','review_count',v=>Math.round(v)],['上架天数中位数','days_since_launch',v=>Math.round(v)+'天'],['价格中位数','price_gbp',v=>money(v)],['子体销量中位数','sales_estimate',v=>Math.round(v)],['≤180天新品占比',null,(v,g)=>pct(ratio(g.filter(x=>(x.days_since_launch??9999)<=180).length,g.length))]];$('thresholdRows').innerHTML=specs.map(([name,key,fn])=>`<tr><td>${name}</td>${groups.map(g=>`<td>${key?(median(g.map(x=>x[key]))==null?'—':fn(median(g.map(x=>x[key])))):fn(null,g)}</td>`).join('')}</tr>`).join('')}
function priceBandStats(){const order=['<£5','£5–6.99','£7–9.99','£10–14.99','≥£15'];return order.map(b=>{const g=products.filter(x=>priceBand(x.price_gbp)===b);return {band:b,n:g.length,topRate:ratio(g.filter(x=>x.category_rank<=100).length,g.length),newRate:ratio(g.filter(x=>(x.days_since_launch??9999)<=180).length,g.length),strongRate:ratio(g.filter(x=>Math.abs(rankDiff(x).delta||0)>=20).length,g.length)}})}
function renderPrice(){ $('priceRows').innerHTML=priceBandStats().map(x=>`<tr><td><b>${x.band}</b></td><td>${x.n}</td><td>${pct(x.topRate)}</td><td>${pct(x.newRate)}</td><td>${pct(x.strongRate)}</td></tr>`).join('')}
function renderBrand(){const counts=new Map();products.forEach(x=>{const b=(x.brand||'').trim();if(b)counts.set(b,(counts.get(b)||0)+1)});const vals=[...counts.values()].sort((a,b)=>b-a),total=products.length,topN=n=>ratio(vals.slice(0,n).reduce((a,b)=>a+b,0),total);$('brandMetrics').innerHTML=[['有效品牌数',counts.size],['Top5占比',pct(topN(5))],['Top10占比',pct(topN(10))]].map(([a,b])=>`<div class="mini-metric"><span>${a}</span><b>${b}</b></div>`).join('');const growth=[...structureRows('product_type'),...structureRows('occasion')].sort((a,b)=>b.growth-a.growth).slice(0,6);$('growthChips').innerHTML=growth.map(x=>`<span class="growth-chip ${x.growth<0?'down':''}">${esc(x.label)} ${x.growth>=0?'+':''}${x.growth.toFixed(2)}pct</span>`).join('')||'<span class="tag">暂无结构趋势</span>'}
function renderOpportunity(){const pool=products.filter(x=>x.category_rank<=600).map(x=>({x,score:opportunityScore(x)})).sort((a,b)=>b.score-a.score).slice(0,10);$('opportunityNote').textContent=`从 ${products.length} 个有效ASIN中筛选`;$('opportunityRows').innerHTML=pool.map(({x,score})=>{const d=rankDiff(x);return `<tr><td>${productCell(x)}</td><td><span class="score-pill">${score}</span></td><td>${opportunityType(x)}</td><td class="rank">#${fmt(x.category_rank)}</td><td>${moveHtml(d)}</td><td class="trend">${trend(x)}</td><td>${fmt(x.days_since_launch)}</td><td>${fmt(x.review_count)}</td><td>${fmt(x.sales_estimate)}</td><td><div class="reason-wrap">${reasons(x)}</div></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">暂无可评分商品。</td></tr>';bindImgs()}
function renderMatrix(){const rows=[...structureRows('product_type'),...structureRows('occasion'),...structureRows('colour_style')].filter(x=>x.label&&!['其他','待细分'].includes(x.label));const med=median(rows.map(x=>x.share))||0;const qs={qEnter:[],qStrong:[],qWatch:[],qMature:[]};rows.forEach(x=>{const highGrowth=x.growth>0,highShare=x.share>=med;const key=highGrowth?(highShare?'qStrong':'qEnter'):(highShare?'qMature':'qWatch');qs[key].push(x)});Object.entries(qs).forEach(([id,a])=>{$(id).innerHTML=a.sort((x,y)=>Math.abs(y.growth)-Math.abs(x.growth)).slice(0,7).map(x=>`<span class="quad-chip">${esc(x.label)} <b>${x.growth>=0?'+':''}${x.growth.toFixed(1)}pt</b></span>`).join('')||'<span class="tag">暂无标签</span>'})}
function renderQuality(){const vals=[['销量覆盖率',pct(ratio(products.filter(x=>x.sales_estimate!=null).length,products.length))],['主图覆盖率',pct(ratio(products.filter(x=>x.image_url).length,products.length))],['评论覆盖率',pct(ratio(products.filter(x=>x.review_count!=null).length,products.length))],['不同BSR位置',new Set(products.filter(x=>x.category_rank<=100).map(x=>x.category_rank)).size]];$('qualityMetrics').innerHTML=vals.map(([a,b])=>`<div class="mini-metric"><span>${a}</span><b>${b}</b></div>`).join('');$('sourceStatus').innerHTML=`<b>状态：</b>${esc(latest.source_status||'unknown')}<br><br>${esc(latest.source_note||'—')}`}

function renderChanges(){const term=$('changeSearch').value.trim().toLowerCase(),type=$('changeType').value,rule=$('changeRule').value;const all=products.filter(x=>rankDiff(x).old!=null&&rankDiff(x).delta!==0||isNewTop(x));const counts={p0:0,p1:0,p2:0,p3:0};all.forEach(x=>counts[priority(x)]++);$('p0Count').textContent=counts.p0;$('p1Count').textContent=counts.p1;$('p2Count').textContent=counts.p2;$('p3Count').textContent=counts.p3;let rows=all.filter(x=>(!term||`${x.asin} ${x.title||''} ${x.brand||''}`.toLowerCase().includes(term))&&(!type||x.product_type===type)&&(!rule||rule==='all'||priority(x)===rule));const po={p0:0,p1:1,p2:2,p3:3};rows.sort((a,b)=>po[priority(a)]-po[priority(b)]||Math.abs(rankDiff(b).delta||0)-Math.abs(rankDiff(a).delta||0));$('changeCount').textContent=`${rows.length} 个发生排名变化`;$('changeRows').innerHTML=rows.map(x=>{const d=rankDiff(x),p=priority(x);return `<tr><td>${productCell(x)}</td><td><span class="priority-badge ${p}">${priorityLabel(p)}</span></td><td class="rank">#${fmt(x.category_rank)}</td><td>${d.old==null?'—':'#'+fmt(d.old)}</td><td>${moveHtml(d)}</td><td>${money(x.price_gbp)}</td><td>${fmt(x.sales_estimate)}</td><td>${x.rating??'—'} / ${fmt(x.review_count)}</td><td>${productTags(x)}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">当前筛选条件下暂无商品。</td></tr>';bindImgs()}
function renderMid(){const term=$('midSearch').value.trim().toLowerCase(),type=$('midType').value,sort=$('midSort').value;let rows=products.filter(x=>x.category_rank>=200&&x.category_rank<=400).filter(x=>(!term||`${x.asin} ${x.title||''} ${x.brand||''}`.toLowerCase().includes(term))&&(!type||x.product_type===type));const counts={p0:0,p1:0,p2:0,p3:0};rows.forEach(x=>{const d=rankDiff(x).delta||0;if(d>=50)counts.p0++;else if(d>=20)counts.p1++;else if(d>0)counts.p2++;else counts.p3++});$('midP0').textContent=counts.p0;$('midP1').textContent=counts.p1;$('midP2').textContent=counts.p2;$('midP3').textContent=counts.p3;$('midCount').textContent=`${rows.length} 个 ASIN`;rows.sort((a,b)=>{if(sort==='rank')return a.category_rank-b.category_rank;if(sort==='sales')return (b.sales_estimate??-1)-(a.sales_estimate??-1);if(sort==='newest')return (a.days_since_launch??99999)-(b.days_since_launch??99999);if(sort==='score')return breakthroughScore(b)-breakthroughScore(a);return (rankDiff(b).delta??-9999)-(rankDiff(a).delta??-9999)});$('midRows').innerHTML=rows.map(x=>{const d=rankDiff(x),p=d.delta>=50?'p0':d.delta>=20?'p1':d.delta>0?'p2':'p3',score=breakthroughScore(x);return `<tr><td>${productCell(x)}</td><td><span class="priority-badge ${p}">${p==='p0'?'P0 快速前移':p==='p1'?'P1 强前移':p==='p2'?'P2 前移':'P3 观察'}</span></td><td class="rank">#${fmt(x.category_rank)}</td><td>${d.old==null?'—':'#'+fmt(d.old)}</td><td>${moveHtml(d)}</td><td>${money(x.price_gbp)}</td><td>${fmt(x.sales_estimate)}</td><td>${fmt(x.days_since_launch)}</td><td><span class="score-pill">${score}</span></td><td>${score>=80?'优先核查连续突破':score>=65?'重点观察':'持续观察'}</td></tr>`}).join('')||'<tr><td colspan="10" class="empty">当前没有 #200–400 数据。</td></tr>';bindImgs()}
function renderStructure(){const rows=structureRows(selectedDim),growth=rows.filter(x=>x.growth>0).sort((a,b)=>b.growth-a.growth),drop=rows.filter(x=>x.growth<0).sort((a,b)=>a.growth-b.growth),main=[...rows].sort((a,b)=>b.share-a.share),newA=rows.filter(x=>x.base===0&&x.share>0);const item=x=>`<div class="structure-item"><b>${esc(x.label)} <span class="${x.growth>=0?'positive':'negative'}">${x.growth>=0?'+':''}${x.growth.toFixed(2)}pct</span></b><small>${x.trend.map(v=>v.toFixed(1)+'%').join(' → ')}</small></div>`;$('fastGrowth').innerHTML=growth.slice(0,5).map(item).join('')||'<div class="empty">暂无增长信号</div>';$('fastDrop').innerHTML=drop.slice(0,5).map(item).join('')||'<div class="empty">暂无下降信号</div>';$('mainstream').innerHTML=main.slice(0,5).map(item).join('')||'<div class="empty">暂无结构数据</div>';$('newAppear').innerHTML=newA.slice(0,5).map(item).join('')||'<div class="empty">暂无明显新出现</div>';$('structureRows').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.label)}</b></td><td>${x.count}</td><td>${x.share.toFixed(2)}%</td><td>${x.base.toFixed(2)}%</td><td class="${x.growth>=0?'positive':'negative'}"><b>${x.growth>=0?'+':''}${x.growth.toFixed(2)}pct</b></td><td>${x.trend.map(v=>v.toFixed(1)+'%').join(' → ')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无结构数据。</td></tr>'}
function fillTypeOptions(){const types=[...new Set(products.map(x=>x.product_type).filter(Boolean))].sort();['changeType','midType'].forEach(id=>{const el=$(id),v=el.value;el.innerHTML='<option value="">全部产品类型</option>'+types.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');el.value=v})}
function bindImgs(){document.querySelectorAll('img.thumb:not([data-b])').forEach(img=>{img.dataset.b='1';img.onerror=()=>{const d=document.createElement('div');d.className='ph';d.innerHTML='图片<br>加载失败';img.replaceWith(d)}})}
function renderAll(){renderHeader();renderRadar();renderNewAbility();renderThreshold();renderPrice();renderBrand();renderOpportunity();renderMatrix();renderQuality();fillTypeOptions();renderChanges();renderMid();renderStructure()}
async function load(){try{$('livePill').textContent='正在读取最新数据…';const all=await q('monitor_runs?select=*&category_key=eq.party_balloons&order=collected_at.desc&limit=12');runs=all.filter(r=>r.source_status==='ok');const live=runs.filter(r=>r.source==='local_chrome_sellersprite');latest=live[0]||runs[0];prev=live[1]||runs[1];prev2=live[2]||runs[2];if(!latest)throw new Error('暂无采集批次');const [cur,p1,p2]=await Promise.all([q(`product_snapshots?select=*&run_id=eq.${latest.id}&order=category_rank.asc.nullslast`),prev?q(`product_snapshots?select=*&run_id=eq.${prev.id}`):Promise.resolve([]),prev2?q(`product_snapshots?select=*&run_id=eq.${prev2.id}`):Promise.resolve([])]);products=cur;prevProducts=p1;prev2Products=p2;prevMap=new Map(p1.map(x=>[x.asin,x]));prev2Map=new Map(p2.map(x=>[x.asin,x]));$('livePill').textContent='● 动态后台已连接';$('livePill').className='status-pill';renderAll()}catch(e){$('livePill').textContent='后台连接异常';$('livePill').className='status-pill warn';$('summaryText').textContent=e.message;console.error(e)}}

document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')}));
['changeSearch','changeType','changeRule'].forEach(id=>$(id).addEventListener(id==='changeSearch'?'input':'change',renderChanges));['midSearch','midType','midSort'].forEach(id=>$(id).addEventListener(id==='midSearch'?'input':'change',renderMid));document.querySelectorAll('#dimChips button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#dimChips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedDim=b.dataset.dim;renderStructure()}));
load();setInterval(load,300000);