/* Definitive history & trend center v2. Loaded last so it can recover from any earlier enhancement failure. */
(function(){
  const css=`
  #detailHistory{padding-top:18px}
  .hist-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;margin:0 0 16px}
  .hist-head h2{margin:0 0 5px;font-size:24px;color:#172033}.hist-head p{margin:0;color:#667085;font-size:12px;line-height:1.6}
  .hist-count{font-size:11px;color:#667085;white-space:nowrap}
  .hist-switch-wrap{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:0 0 16px;padding:5px;background:#eef2f7;border:1px solid #e1e6ef;border-radius:13px;width:max-content;max-width:100%}
  .hist-switch{display:flex;gap:4px;flex-wrap:wrap}
  .hist-switch button{appearance:none;border:0;background:transparent;color:#667085;padding:9px 14px;border-radius:9px;font-size:12px;font-weight:800;cursor:pointer;transition:.15s ease;white-space:nowrap}
  .hist-switch button:hover{background:#fff;color:#344054}.hist-switch button.active{background:#172033;color:#fff;box-shadow:0 1px 2px rgba(16,24,40,.12)}
  .hist-custom{display:none;align-items:center;gap:7px;margin-left:6px}.hist-custom.show{display:flex}.hist-custom input{border:1px solid #d0d5dd;background:#fff;border-radius:8px;padding:7px 9px;font-size:11px;color:#344054}
  .hist-custom button{border:0;background:#245dd8;color:#fff;border-radius:8px;padding:8px 11px;font-size:11px;font-weight:800;cursor:pointer}
  .hist-summary{display:flex;gap:12px;align-items:flex-start;border:1px solid #cbd8f3;background:#f7f9ff;border-radius:14px;padding:15px 16px;margin:0 0 14px}
  .hist-summary-mark{width:30px;height:30px;border-radius:9px;background:#e8f0ff;color:#245dd8;display:grid;place-items:center;font-weight:900;flex:0 0 auto}
  .hist-summary .k{font-size:10px;font-weight:850;color:#245dd8;margin-bottom:5px}.hist-summary .t{font-size:13px;line-height:1.7;color:#27364d;font-weight:650}
  .hist-note{font-size:11px;color:#667085;margin:-4px 0 12px}
  .hist-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:0 0 14px}
  .hist-kpi{background:#fff;border:1px solid #e1e6ef;border-radius:13px;padding:13px 14px}.hist-kpi span{display:block;color:#667085;font-size:10px;margin-bottom:6px}.hist-kpi b{display:block;color:#172033;font-size:20px;line-height:1.15}.hist-kpi small{display:block;color:#98a2b3;font-size:10px;margin-top:5px;line-height:1.45}
  .hist-up{color:#067647!important}.hist-down{color:#c43228!important}.hist-flat{color:#667085!important}
  .hist-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:0 0 14px}
  .hist-card{background:#fff;border:1px solid #e1e6ef;border-radius:14px;padding:14px}.hist-card h3{margin:0 0 3px;font-size:13px;color:#172033}.hist-card>p{margin:0 0 12px;font-size:10px;color:#667085;line-height:1.5}
  .hist-bars{display:flex;align-items:flex-end;gap:7px;height:118px}.hist-bar-item{flex:1;min-width:0;text-align:center}.hist-bar-box{height:78px;display:flex;align-items:flex-end;justify-content:center}.hist-bar{width:72%;min-height:4px;background:#cbd8f3;border-radius:5px 5px 2px 2px}.hist-val{display:block;font-size:10px;font-weight:800;color:#344054;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hist-date{display:block;font-size:9px;color:#98a2b3;margin-top:3px}
  .hist-section{background:#fff;border:1px solid #e1e6ef;border-radius:14px;padding:14px;margin:0 0 14px}.hist-section-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.hist-section-head h3{margin:0 0 3px;font-size:14px;color:#172033}.hist-section-head p{margin:0;color:#667085;font-size:10px}
  .hist-dims{display:flex;gap:5px;flex-wrap:wrap}.hist-dims button{border:1px solid #d7deea;background:#fff;color:#667085;border-radius:999px;padding:6px 9px;font-size:10px;font-weight:800;cursor:pointer}.hist-dims button.active{background:#eef4ff;border-color:#b8ccff;color:#245dd8}
  .hist-change{display:grid;grid-template-columns:minmax(130px,1.5fr) 90px 90px 90px;gap:8px;align-items:center;border-top:1px solid #eef1f5;padding:8px 0;font-size:11px}.hist-change:first-child{border-top:0}.hist-change .n{font-weight:800;color:#344054}.hist-change .brand{color:#174ea6}.hist-change .num{text-align:right;color:#667085}.hist-change .delta{text-align:right;font-weight:850}
  .hist-winner{display:grid;grid-template-columns:minmax(0,1fr) 120px 140px;gap:10px;align-items:center;border-top:1px solid #eef1f5;padding:9px 0}.hist-winner:first-child{border-top:0}.hist-signal{font-size:10px;font-weight:800;color:#245dd8;background:#eef4ff;border-radius:999px;padding:5px 8px;text-align:center}.hist-rank{text-align:right;font-size:10px;color:#667085;line-height:1.55}
  .hist-batch-tools{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:0 0 12px}.hist-batch-tools select{min-width:320px;max-width:100%;border:1px solid #d0d5dd;background:#fff;border-radius:9px;padding:9px 11px;font-size:11px;color:#344054;font-weight:700}.hist-batch-note{font-size:10px;color:#667085}
  .hist-empty{padding:26px;text-align:center;color:#667085;font-size:12px}.hist-view{display:none}.hist-view.active{display:block}
  .product-meta-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:5px}.asin-code{font-size:10px;color:#98a2b3;font-weight:600}.brand-highlight{display:inline-flex;align-items:center;max-width:190px;padding:2px 8px;border:1px solid #b8ccff;border-radius:999px;background:#eef4ff;color:#174ea6;font-size:11px;font-weight:850;line-height:1.5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  @media(max-width:900px){.hist-kpis{grid-template-columns:1fr 1fr}.hist-grid{grid-template-columns:1fr}.hist-winner{grid-template-columns:1fr}.hist-rank{text-align:left}.hist-switch-wrap{width:100%}}
  @media(max-width:620px){.hist-switch-wrap{overflow:auto;flex-wrap:nowrap}.hist-switch{flex-wrap:nowrap}.hist-switch button{padding:8px 11px}.hist-change{grid-template-columns:1fr 65px 70px}.hist-change .start{display:none}.hist-kpis{grid-template-columns:1fr 1fr}}
  `;
  let style=document.getElementById('hist-v2-style');if(!style){style=document.createElement('style');style.id='hist-v2-style';style.textContent=css;document.head.appendChild(style)}

  if(typeof productCell==='function'){
    productCell=function(x){
      const link=safe(x.source_url)||`https://www.amazon.co.uk/dp/${encodeURIComponent(x.asin)}`,img=safe(x.image_url);
      return `<div class="product">${img?`<img class="thumb" loading="lazy" src="${esc(img)}" alt="">`:'<div class="ph">暂无<br>主图</div>'}<div><div class="ptitle"><a href="${esc(link)}" target="_blank" rel="noopener">${esc(x.title||'未获取标题')}</a></div><div class="product-meta-row"><span class="asin-code">${esc(x.asin)}</span>${x.brand?`<span class="brand-highlight">${esc(x.brand)}</span>`:''}</div></div></div>`;
    };
  }

  const compact=n=>n==null||!Number.isFinite(Number(n))?'—':Math.abs(Number(n))>=1e6?(Number(n)/1e6).toFixed(2).replace(/\.00$/,'')+'M':Math.abs(Number(n))>=1e3?(Number(n)/1e3).toFixed(1).replace(/\.0$/,'')+'K':Math.round(Number(n)).toLocaleString('en-GB');
  const gbp=n=>n==null||!Number.isFinite(Number(n))?'—':'£'+compact(n);
  const med=a=>{const x=a.filter(v=>v!=null&&Number.isFinite(Number(v))).map(Number).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
  const norm=s=>String(s||'未知品牌').trim().toLowerCase();
  const dateOnly=s=>new Date(s).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'});
  const lowValue=x=>typeof isLowValueOldListing==='function'?isLowValueOldListing(x):(x.days_since_launch!=null&&Number(x.days_since_launch)>365&&x.parent_sales_estimate!=null&&Number(x.parent_sales_estimate)<300);
  const clean=rows=>(rows||[]).filter(x=>!lowValue(x));
  function parentKey(x){return x.parent_asin?'p:'+x.parent_asin:['h',norm(x.brand),x.category_rank??'na',x.parent_sales_estimate??'na',x.variant_count??'na'].join('|')}
  function snap(rows){
    rows=clean(rows);const m=new Map();
    for(const x of rows){const k=parentKey(x);let g=m.get(k);if(!g){g={brand:x.brand||'未知品牌',rank:x.category_rank??null,sales:null,revenues:[],prices:[]};m.set(k,g)}if(x.parent_sales_estimate!=null)g.sales=Math.max(g.sales??-Infinity,Number(x.parent_sales_estimate));if(x.sales_revenue_gbp!=null)g.revenues.push(Number(x.sales_revenue_gbp));if(x.price_gbp!=null)g.prices.push(Number(x.price_gbp))}
    const gs=[...m.values()].map(g=>{g.revenue=med(g.revenues);if(g.revenue==null&&g.sales!=null){const p=med(g.prices);if(p!=null)g.revenue=g.sales*p}return g}),known=gs.filter(g=>g.sales!=null&&Number.isFinite(g.sales)),knownRev=gs.filter(g=>g.revenue!=null&&Number.isFinite(g.revenue));
    const totalSales=known.length?known.reduce((s,g)=>s+g.sales,0):null,totalRevenue=knownRev.length?knownRev.reduce((s,g)=>s+g.revenue,0):null,bm=new Map();
    for(const g of known){if(!g.brand||g.brand==='未知品牌')continue;const k=norm(g.brand),o=bm.get(k)||{name:g.brand,sales:0};o.sales+=g.sales;bm.set(k,o)}
    const brands=[...bm.values()].sort((a,b)=>b.sales-a.sales).map(x=>({...x,share:totalSales?100*x.sales/totalSales:0})),top=rows.filter(x=>x.category_rank!=null&&x.category_rank<=100),young=top.filter(x=>x.days_since_launch!=null&&x.days_since_launch<=180);
    return {rows,totalSales,totalRevenue,parentCount:gs.length,price:med(rows.map(x=>x.price_gbp)),brands,cr3:brands.slice(0,3).reduce((s,x)=>s+x.share,0),youngShare:top.length?100*young.length/top.length:0,topCount:top.length,salesCoverage:gs.length?100*known.length/gs.length:0};
  }
  function dp(cur,old){return cur==null||old==null||!Number.isFinite(Number(cur))||!Number.isFinite(Number(old))||Number(old)===0?null:100*(Number(cur)-Number(old))/Number(old)}
  function dpp(cur,old){return cur==null||old==null?null:Number(cur)-Number(old)}
  function delta(v,suffix='%'){if(v==null||!Number.isFinite(v))return'<span class="hist-flat">历史不足</span>';return `<span class="${v>0?'hist-up':v<0?'hist-down':'hist-flat'}">${v>0?'↑ +':v<0?'↓ ':'→ '}${v.toFixed(1)}${suffix}</span>`}
  function ages(x){const s=`${x.title||''} ${x.occasion||''}`,out=new Set();if(!/birthday|bday|生日/i.test(s))return[];for(const re of [/\b(\d{1,3})(?:st|nd|rd|th)\s+(?:birthday|bday)\b/ig,/\b(?:birthday|bday).*?\b(\d{1,3})(?:st|nd|rd|th)?\b/ig]){let m;while((m=re.exec(s))){const n=Number(m[1]);if(n>=1&&n<=120)out.add(n+'岁')}}return[...out]}
  function themes(x){if(typeof extractThemes==='function')return extractThemes(x);const s=`${x.title||''} ${x.occasion||''}`.toLowerCase(),a=[];if(/birthday|bday/.test(s))a.push('生日');for(const [n,re]of[['Baby Shower',/baby shower/],['婚礼',/wedding/],['Hen Party',/hen party/],['毕业',/graduation/],['足球',/football|soccer/],['恐龙',/dinosaur/],['公主',/princess/],['彩虹',/rainbow/],['游戏',/gaming|gamer/]])if(re.test(s))a.push(n);return a}
  function tags(x,dim){if(dim==='age')return ages(x);if(dim==='theme')return themes(x);return String(x?.[dim]||'').split(/[\/|,;]/).map(v=>v.trim()).filter(Boolean)}
  function shares(rows,dim){rows=clean(rows);const base=dim==='age'?rows.filter(x=>/birthday|bday|生日/i.test(`${x.title||''} ${x.occasion||''}`)):rows,m=new Map();for(const x of base)for(const t of tags(x,dim))m.set(t,(m.get(t)||0)+1);const o=new Map();for(const[k,n]of m)o.set(k,{count:n,share:base.length?100*n/base.length:0});return o}

  let runs=[],cache=new Map(),mode='30d',dim='theme',state=null,currentKey=null;
  async function rowsFor(id){if(cache.has(id))return cache.get(id);const rows=await q(`product_snapshots?select=*&run_id=eq.${id}&order=category_rank.asc.nullslast`);cache.set(id,rows);return rows}
  function ensureUI(){
    const tabs=document.querySelector('.detail-tabs'),detail=document.getElementById('detailPanel');if(!tabs||!detail)return false;
    let old=document.getElementById('historyTabButton'),btn;
    if(old){btn=old.cloneNode(true);old.replaceWith(btn)}else{btn=document.createElement('button');btn.id='historyTabButton';btn.type='button';btn.textContent='历史与趋势';tabs.appendChild(btn)}
    let panel=document.getElementById('detailHistory');if(!panel){panel=document.createElement('section');panel.id='detailHistory';panel.className='detail-panel';detail.appendChild(panel)}
    panel.innerHTML=`<div class="hist-head"><div><h2>历史与趋势</h2><p>原始批次用于查证；7天、30天和季度用于回顾市场、品牌、结构与产品开发信号。</p></div><div id="histCount" class="hist-count">准备读取历史…</div></div>
    <div class="hist-switch-wrap"><div id="histSwitch" class="hist-switch"><button data-m="batch">原始批次</button><button data-m="7d">近7天</button><button class="active" data-m="30d">近30天</button><button data-m="quarter">本季度</button><button data-m="custom">自定义</button></div><div id="histCustom" class="hist-custom"><input id="histStart" type="date"><span>—</span><input id="histEnd" type="date"><button id="histApply">应用</button></div></div>
    <div id="histTrend" class="hist-view active"><div class="hist-summary"><div class="hist-summary-mark">✦</div><div><div class="k">时间维度开发结论</div><div id="histSummary" class="t">正在读取历史数据…</div></div></div><div id="histNote" class="hist-note"></div><div id="histKpis" class="hist-kpis"></div><div id="histCharts" class="hist-grid"></div><div class="hist-section"><div class="hist-section-head"><div><h3>品牌份额变化</h3><p>按父体销量口径比较期初与当前。</p></div></div><div id="histBrands"></div></div><div class="hist-section"><div class="hist-section-head"><div><h3>产品结构变化</h3><p>寻找多轮持续变化的产品开发方向。</p></div><div id="histDims" class="hist-dims"><button data-d="product_type">产品类型</button><button class="active" data-d="theme">主题</button><button data-d="age">年龄</button><button data-d="colour_style">颜色</button><button data-d="pack_size">数量</button><button data-d="size_text">尺寸</button><button data-d="occasion">场景</button><button data-d="material">材质</button></div></div><div id="histStruct"></div></div><div class="hist-section"><div class="hist-section-head"><div><h3>时间段赢家 ASIN</h3><p>根据进入 Top100、排名前移、新品与父体销量综合排序，但不输出机会分。</p></div></div><div id="histWinners"></div></div></div>
    <div id="histBatch" class="hist-view"><div class="hist-batch-tools"><select id="histRunSelect"><option>正在读取历史批次…</option></select><span id="histBatchNote" class="hist-batch-note"></span></div><div id="histBatchKpis" class="hist-kpis"></div><div class="table-wrap"><table class="product-table"><thead><tr><th>商品</th><th>当前排名</th><th>父体销量</th><th>销售额</th><th>变体数量</th><th>上架天数</th></tr></thead><tbody id="histRows"><tr><td colspan="6" class="hist-empty">选择一个批次查看。</td></tr></tbody></table></div></div>`;
    btn.addEventListener('click',async()=>{document.querySelectorAll('.detail-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#detailPanel>.detail-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');panel.classList.add('active');await loadRuns(activeKey)});
    document.getElementById('histSwitch').addEventListener('click',e=>{const b=e.target.closest('button[data-m]');if(b)setMode(b.dataset.m)});
    document.getElementById('histDims').addEventListener('click',e=>{const b=e.target.closest('button[data-d]');if(!b)return;dim=b.dataset.d;document.querySelectorAll('#histDims button').forEach(x=>x.classList.toggle('active',x===b));renderStruct()});
    document.getElementById('histRunSelect').addEventListener('change',e=>renderBatch(Number(e.target.value)));
    document.getElementById('histApply').addEventListener('click',()=>renderTrend('custom'));
    return true;
  }
  function setMode(m){mode=m;document.querySelectorAll('#histSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.m===m));document.getElementById('histTrend').classList.toggle('active',m!=='batch');document.getElementById('histBatch').classList.toggle('active',m==='batch');document.getElementById('histCustom').classList.toggle('show',m==='custom');if(m==='batch'){const s=document.getElementById('histRunSelect');if(s?.value)renderBatch(Number(s.value))}else if(m==='custom')initDates();else renderTrend(m)}
  function initDates(){if(!runs.length)return;const end=new Date(runs[0].collected_at),start=new Date(end.getTime()-30*86400000);const f=d=>d.toISOString().slice(0,10);document.getElementById('histStart').value=f(start);document.getElementById('histEnd').value=f(end)}
  function runBefore(ts){return runs.find(r=>new Date(r.collected_at).getTime()<=ts)||runs[runs.length-1]||null}
  function range(m){if(!runs.length)return null;const end=new Date(runs[0].collected_at),et=end.getTime();if(m==='custom'){const a=document.getElementById('histStart').value,b=document.getElementById('histEnd').value;if(!a||!b)return null;return{start:new Date(a+'T00:00:00').getTime(),end:new Date(b+'T23:59:59').getTime(),label:`${a} 至 ${b}`}}let st;if(m==='7d')st=et-7*86400000;else if(m==='30d')st=et-30*86400000;else st=new Date(end.getFullYear(),Math.floor(end.getMonth()/3)*3,1).getTime();return{start:st,end:et,label:m==='7d'?'近7天':m==='30d'?'近30天':'本季度'}}
  function pickPoints(sr,er,r){let a=runs.filter(x=>{const t=new Date(x.collected_at).getTime();return t>=new Date(sr.collected_at).getTime()&&t<=new Date(er.collected_at).getTime()}).sort((x,y)=>new Date(x.collected_at)-new Date(y.collected_at));if(!a.some(x=>x.id===sr.id))a.unshift(sr);if(!a.some(x=>x.id===er.id))a.push(er);a=[...new Map(a.map(x=>[x.id,x])).values()];if(a.length<=7)return a;return[...new Map(Array.from({length:7},(_,i)=>a[Math.round(i*(a.length-1)/6)]).map(x=>[x.id,x])).values()]}
  async function loadRuns(key){
    currentKey=key;cache=new Map();document.getElementById('histSummary').textContent='正在读取历史数据…';
    try{runs=await q(`monitor_runs?select=id,collected_at,source,source_status,source_note,data_month&category_key=eq.${key}&order=collected_at.desc&limit=120`);document.getElementById('histCount').textContent=`已保留 ${runs.length} 个采集批次`;const s=document.getElementById('histRunSelect');s.innerHTML=runs.map((r,i)=>`<option value="${r.id}">${i===0?'最新 · ':''}${when(r.collected_at)} · Run ${r.id}</option>`).join('');if(!runs.length){document.getElementById('histSummary').textContent='当前类目还没有历史批次。';return}if(mode==='batch')await renderBatch(runs[0].id);else await renderTrend(mode)}catch(e){document.getElementById('histSummary').textContent='历史读取失败：'+e.message}
  }
  async function renderBatch(id){const r=runs.find(x=>Number(x.id)===Number(id));try{const rows=await rowsFor(id),s=snap(rows),pc=rows.length?100*rows.filter(x=>x.parent_sales_estimate!=null).length/rows.length:0;document.getElementById('histBatchNote').textContent=r?`${when(r.collected_at)} · ${r.source_status||'未标记状态'}`:'';document.getElementById('histBatchKpis').innerHTML=[['该轮 ASIN',fmt(rows.length),'原始快照'],['排名≤100',fmt(s.topCount),'该轮采集'],['父体销量覆盖',pc.toFixed(1)+'%','卖家精灵字段'],['有效父体',fmt(s.parentCount),'去重估算']].map(x=>`<div class="hist-kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');document.getElementById('histRows').innerHTML=rows.length?rows.map(x=>`<tr><td>${productCell(x)}</td><td class="rank">${x.category_rank==null?'—':'#'+fmt(x.category_rank)}</td><td>${x.parent_sales_estimate==null?'—':fmt(x.parent_sales_estimate)}</td><td>${x.sales_revenue_gbp==null?'—':money(x.sales_revenue_gbp)}</td><td>${x.variant_count==null?'—':fmt(x.variant_count)}</td><td>${fmt(x.days_since_launch)}</td></tr>`).join(''):'<tr><td colspan="6" class="hist-empty">该批次没有商品记录。</td></tr>';bindImgs()}catch(e){document.getElementById('histRows').innerHTML=`<tr><td colspan="6" class="hist-empty">读取失败：${esc(e.message)}</td></tr>`}}
  async function renderTrend(m){if(!runs.length)return;const rg=range(m);if(!rg)return;const er=runBefore(rg.end)||runs[0],sr=runBefore(rg.start)||runs[runs.length-1];document.getElementById('histSummary').textContent='正在计算市场、品牌和结构变化…';try{const pts=pickPoints(sr,er,rg),bundle=await Promise.all(pts.map(async r=>({run:r,s:snap(await rowsFor(r.id))}))),startRows=await rowsFor(sr.id),endRows=await rowsFor(er.id);state={label:rg.label,sr,er,startRows,endRows,start:snap(startRows),end:snap(endRows),pts:bundle};renderTrendAll()}catch(e){document.getElementById('histSummary').textContent='趋势读取失败：'+e.message}}
  function chart(title,desc,pts,get,format){const vals=pts.map(p=>get(p.s)).filter(v=>v!=null&&Number.isFinite(Number(v))).map(Number);if(!vals.length)return`<div class="hist-card"><h3>${title}</h3><p>${desc}</p><div class="hist-empty">该时间段缺少可用字段。</div></div>`;const max=Math.max(...vals),min=Math.min(...vals),span=Math.max(1,max-min);return`<div class="hist-card"><h3>${title}</h3><p>${desc}</p><div class="hist-bars">${pts.map(p=>{const v=get(p.s),h=v==null?4:Math.max(6,12+60*(Number(v)-min)/span);return`<div class="hist-bar-item"><div class="hist-bar-box"><div class="hist-bar" style="height:${h}px"></div></div><span class="hist-val">${format(v)}</span><span class="hist-date">${dateOnly(p.run.collected_at)}</span></div>`}).join('')}</div></div>`}
  function winners(st){const sm=new Map(st.startRows.map(x=>[x.asin,x]));return clean(st.endRows).map(x=>{const old=sm.get(x.asin),or=old?.category_rank??null,d=or!=null&&x.category_rank!=null?or-x.category_rank:null,newTop=x.category_rank<=100&&(or==null||or>100),young=x.days_since_launch!=null&&x.days_since_launch<=180;const signal=newTop?'新进 Top100':d>=100?'排名大幅前移':d>=20?'持续前移':young&&x.category_rank<=100?'新品进入头部':'当前头部';const score=(newTop?10000:0)+(d??0)+(young?300:0)+(x.parent_sales_estimate??0)/50;return{x,or,d,signal,score}}).filter(o=>o.x.category_rank!=null&&(o.signal!=='当前头部'||o.x.category_rank<=100)).sort((a,b)=>b.score-a.score).slice(0,8)}
  function summary(st){const dimBest=d=>{const a=shares(st.startRows,d),b=shares(st.endRows,d);let z=null;for(const[k,v]of b){const dv=v.share-(a.get(k)?.share||0);if(!z||dv>z.dv)z={k,dv}}return z},th=dimBest('theme'),ag=dimBest('age'),ty=dimBest('product_type'),w=winners(st)[0],parts=[];if(th&&th.dv>.3)parts.push(`“${th.k}”主题 +${th.dv.toFixed(1)}pct`);if(ag&&ag.dv>.3)parts.push(`${ag.k}生日 +${ag.dv.toFixed(1)}pct`);if(ty&&ty.dv>.3)parts.push(`${ty.k}产品形态 +${ty.dv.toFixed(1)}pct`);let s=`${st.label}回顾：${parts.length?parts.slice(0,3).join('，'):'暂未出现特别集中的单一结构增量'}。`;if(w)s+=`重点关注 ${w.x.brand||'未知品牌'} 的 ${w.x.asin}，排名 ${w.or==null?'新出现':'#'+fmt(w.or)} → #${fmt(w.x.category_rank)}，父体销量 ${w.x.parent_sales_estimate==null?'待补':fmt(w.x.parent_sales_estimate)}。`;s+=ag&&ag.dv>.3?`开发上优先验证 ${ag.k}及相邻年龄段，并同步验证组件组合、安装效率与拍照呈现。`:'开发上优先跟踪多轮同时上涨的产品结构，避免把一次排名跳升当成趋势。';return s}
  function renderTrendAll(){const st=state,days=Math.max(0,Math.round((new Date(st.er.collected_at)-new Date(st.sr.collected_at))/86400000));document.getElementById('histSummary').textContent=summary(st);document.getElementById('histNote').textContent=`${st.label} · ${when(st.sr.collected_at)} → ${when(st.er.collected_at)} · 实际可用跨度 ${days} 天${days<3?' · 当前历史积累较短，趋势仅作早期观察':''}`;const cards=[['父体销量',compact(st.end.totalSales),delta(dp(st.end.totalSales,st.start.totalSales)),'期初 '+compact(st.start.totalSales)],['父体销售额',gbp(st.end.totalRevenue),delta(dp(st.end.totalRevenue,st.start.totalRevenue)),'期初 '+gbp(st.start.totalRevenue)],['有效父体数',fmt(st.end.parentCount),delta(dp(st.end.parentCount,st.start.parentCount)),'期初 '+fmt(st.start.parentCount)],['价格中位数',st.end.price==null?'—':money(st.end.price),delta(dp(st.end.price,st.start.price)),'期初 '+(st.start.price==null?'—':money(st.start.price))],['TOP3品牌集中度',st.end.cr3.toFixed(1)+'%',delta(dpp(st.end.cr3,st.start.cr3),'pct'),'期初 '+st.start.cr3.toFixed(1)+'%'],['Top100新品占比',st.end.youngShare.toFixed(1)+'%',delta(dpp(st.end.youngShare,st.start.youngShare),'pct'),'≤180天新品'],['Top100样本',fmt(st.end.topCount),delta(dp(st.end.topCount,st.start.topCount)),'期初 '+fmt(st.start.topCount)],['父体销量覆盖',st.end.salesCoverage.toFixed(1)+'%','<span class="hist-flat">当前批次</span>','决定销量趋势可信度']];document.getElementById('histKpis').innerHTML=cards.map(x=>`<div class="hist-kpi"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]} · ${x[3]}</small></div>`).join('');document.getElementById('histCharts').innerHTML=chart('父体销量走势','各批次的近30天父体销量估算，不进行逐日累计。',st.pts,s=>s.totalSales,compact)+chart('父体销售额走势','观察期初到当前的方向，而不是把批次相加。',st.pts,s=>s.totalRevenue,gbp)+chart('Top100新品占比','≤180天新品占 Top100 样本比例。',st.pts,s=>s.youngShare,v=>v==null?'—':v.toFixed(1)+'%')+chart('TOP3品牌集中度','观察头部品牌是否持续抢占份额。',st.pts,s=>s.cr3,v=>v==null?'—':v.toFixed(1)+'%');renderBrands();renderStruct();renderWinners()}
  function renderBrands(){if(!state)return;const a=new Map(state.start.brands.map(x=>[norm(x.name),x])),b=new Map(state.end.brands.map(x=>[norm(x.name),x])),keys=new Set([...a.keys(),...b.keys()]);const rows=[...keys].map(k=>{const x=a.get(k),y=b.get(k);return{name:y?.name||x?.name||k,start:x?.share||0,end:y?.share||0,d:(y?.share||0)-(x?.share||0)}}).sort((x,y)=>Math.abs(y.d)-Math.abs(x.d)||y.end-x.end).slice(0,10);document.getElementById('histBrands').innerHTML=rows.length?rows.map(x=>`<div class="hist-change"><span class="n brand">${esc(x.name)}</span><span class="num start">${x.start.toFixed(1)}%</span><span class="num">${x.end.toFixed(1)}%</span><span class="delta ${x.d>=0?'hist-up':'hist-down'}">${x.d>=0?'+':''}${x.d.toFixed(1)}pct</span></div>`).join(''):'<div class="hist-empty">父体销量字段不足，暂时无法计算品牌份额。</div>'}
  function renderStruct(){if(!state)return;const a=shares(state.startRows,dim),b=shares(state.endRows,dim),keys=new Set([...a.keys(),...b.keys()]);const rows=[...keys].map(k=>({name:k,start:a.get(k)?.share||0,end:b.get(k)?.share||0,d:(b.get(k)?.share||0)-(a.get(k)?.share||0)})).filter(x=>x.start>0||x.end>0).sort((x,y)=>Math.abs(y.d)-Math.abs(x.d)||y.end-x.end).slice(0,12);document.getElementById('histStruct').innerHTML=rows.length?rows.map(x=>`<div class="hist-change"><span class="n">${esc(x.name)}</span><span class="num start">${x.start.toFixed(1)}%</span><span class="num">${x.end.toFixed(1)}%</span><span class="delta ${x.d>=0?'hist-up':'hist-down'}">${x.d>=0?'+':''}${x.d.toFixed(1)}pct</span></div>`).join(''):'<div class="hist-empty">当前维度暂无可比较数据。</div>'}
  function renderWinners(){if(!state)return;const rows=winners(state);document.getElementById('histWinners').innerHTML=rows.length?rows.map(o=>`<div class="hist-winner"><div>${productCell(o.x)}</div><span class="hist-signal">${o.signal}</span><div class="hist-rank">${o.or==null?'新出现':'#'+fmt(o.or)} → #${fmt(o.x.category_rank)}<br>父体销量 ${o.x.parent_sales_estimate==null?'—':fmt(o.x.parent_sales_estimate)}</div></div>`).join(''):'<div class="hist-empty">该时间段暂无明显赢家 ASIN。</div>';bindImgs()}

  if(!ensureUI())return;
  document.querySelectorAll('.category-tabs button').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(document.getElementById('historyTabButton')?.classList.contains('active')&&b.dataset.category!=='compare')loadRuns(b.dataset.category)},50)));
})();